### PR TITLE
Update with ros2/geometry

### PR DESCRIPTION
**Pull request by ahcorde**

### CODE REVIEW

**Comment by ahcorde** [comment]
ping

**Comment by vmayoral** [comment]
Reviewing

**Review by anasarrak — APPROVED** [review]

**Comment by anasarrak** [comment]
It compiles everything for me

**Comment by vmayoral** [comment]
My first reaction is that this is problematic because the "most updated" branch in master which contains bits also from other PRs. See 
- https://github.com/ros2/geometry2/pull/93 and
- https://github.com/ros2/geometry2/pull/90 (this branch)

I'm seeing what's the impact on the master branch. Please hold it for now.

**Comment by vmayoral** [comment]
Closed on behalf of https://github.com/AcutronicRobotics/geometry2/pull/5

**Pull request closed without merging**
